feeds:
  interval: 900
  publicBasePath: https://feeds.martingansler.de

spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            clientName: GitLab
            clientId: change_me
            clientSecret: change_me
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorizationGrantType: authorization_code
            scope:
              - read_user
        provider:
          gitlab:
            authorizationUri: https://git.martingansler.de/oauth/authorize
            tokenUri: https://git.martingansler.de/oauth/token
            userInfoUri: https://git.martingansler.de/api/v4/user
            userNameAttribute: username

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/feeds
    username: postgres
    password: super_secret
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

graphql:
  servlet:
    subscriptions:
      websocket:
        path: /subscriptions
    cors:
      allowed-origins:
        - https://feeds.martingansler.de

graphiql:
  enabled: false
voyager:
  enabled: false
