approvedGitRepositories:
  - '**'

enableGlobalCache: false

enableScripts: true

httpRetry: 5

httpTimeout: 100000

networkConcurrency: 8

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.18.0.cjs
