module.exports = {
  projects: [
    '<rootDir>/apps/feeds/core',
    '<rootDir>/apps/feeds/discover-ms',
    '<rootDir>/apps/feeds/frontend',
    '<rootDir>/apps/feeds/fetch-ms',
    '<rootDir>/apps/github-pipeline-status',
    '<rootDir>/apps/quick-zoom',
    '<rootDir>/libs/article',
    '<rootDir>/libs/authentication',
    '<rootDir>/libs/components',
    '<rootDir>/libs/conference-links',
    '<rootDir>/libs/database',
    '<rootDir>/libs/discover',
    '<rootDir>/libs/dom-utils',
    '<rootDir>/libs/feed',
    '<rootDir>/libs/feeds-schema',
    '<rootDir>/libs/fetch',
    '<rootDir>/libs/github-hooks',
    '<rootDir>/libs/github-schema',
    '<rootDir>/libs/hooks',
    '<rootDir>/libs/user',
  ],
}
