module.exports = {
  projects: [
    '<rootDir>/libs/feeds/feeds/core',
    '<rootDir>/libs/feeds/feeds/discover-ms',
    '<rootDir>/libs/feeds/feeds/frontend',
    '<rootDir>/libs/feeds/feeds/fetch-ms',
    '<rootDir>/apps/github-pipeline-status',
    '<rootDir>/apps/quick-zoom',
    '<rootDir>/libs/feeds/feeds/article',
    '<rootDir>/libs/feeds/authentication',
    '<rootDir>/libs/components',
    '<rootDir>/libs/conference-links',
    '<rootDir>/libs/feeds/database',
    '<rootDir>/libs/feeds/discover',
    '<rootDir>/libs/dom-utils',
    '<rootDir>/libs/feeds/feed',
    '<rootDir>/libs/feeds/feeds-schema',
    '<rootDir>/libs/feeds/fetch',
    '<rootDir>/libs/github-hooks',
    '<rootDir>/libs/github-schema',
    '<rootDir>/libs/hooks',
    '<rootDir>/libs/feeds/user',
  ],
}
