image: node:20-alpine

elgato:deploy:
  cache: []
  stage: deploy
  tags:
    - elgato
  #  only:
  #    - main
  before_script:
    - source ~/.nvm/nvm.sh
    - yarn install
  script:
    - yarn nx run elgato-app:build
    - docker compose -f apps/elgato/app/docker-compose.yml up -d
