image: node:21-alpine

elgato:deploy:
  cache: []
  stage: deploy
  needs:
    - lint
  tags:
    - elgato
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
  before_script:
    - source ~/.nvm/nvm.sh
    - yarn install
  script:
    - yarn nx run elgato-app:build
    - docker compose -f apps/elgato/elgato/docker-compose.yml up -d
