name: Prepare NodeJS
description: Installs node dependencies and sets up cache

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6.0.0
      with:
        node-version: '22.21.1'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
