name: Prepare NodeJS
description: Installs node dependencies and sets up cache

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
