/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * stgtrails API
 * OpenAPI spec version: 0.1
 */
import { z as zod } from 'zod'

export const createTrailAreaResponse = zod
  .object({
    id: zod.number(),
    name: zod.string(),
    latitude: zod.number(),
    longitude: zod.number(),
  })
  .strict()

export const getTrailAreasResponseItem = zod
  .object({
    id: zod.number(),
    name: zod.string(),
    latitude: zod.number(),
    longitude: zod.number(),
  })
  .strict()
export const getTrailAreasResponse = zod.array(getTrailAreasResponseItem)

export const createTrailResponse = zod
  .object({
    id: zod.number(),
    name: zod.string(),
    trailAreaId: zod.number(),
  })
  .strict()

export const getTrailsOfAreaResponseItem = zod
  .object({
    id: zod.number(),
    name: zod.string(),
    trailAreaId: zod.number(),
  })
  .strict()
export const getTrailsOfAreaResponse = zod.array(getTrailsOfAreaResponseItem)

export const getWeatherDataForTrailAreaResponseItem = zod
  .object({
    time: zod.string().datetime(),
    temperature2m: zod.number(),
    rain: zod.number(),
    soilMoisture0To1cm: zod.number(),
    soilMoisture1To3cm: zod.number(),
    soilMoisture3To9cm: zod.number(),
    soilMoisture9To27cm: zod.number(),
  })
  .strict()
export const getWeatherDataForTrailAreaResponse = zod.array(getWeatherDataForTrailAreaResponseItem)
