services:
  app:
    image: ${DOCKER_IMAGE_NAME}
    restart: on-failure
    environment:
      TZ: 'Europe/Berlin'
      STGTRAILS_DATABASE_URL: 'file:/usr/stgtrails/sqlite/stgtrails.db'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${STGTRAILS_ADMIN_PASSWORD}
    volumes:
      - sqlite:/usr/stgtrails/sqlite/
    labels:
      - 'traefik.http.services.stgtrails-app.loadbalancer.server.port=3104'
      - 'traefik.http.routers.stgtrails-app.rule=HostRegexp(`^stgtrails(\.martingansler)?\.de`)'
      - 'traefik.http.routers.stgtrails-app.tls=true'
      - 'traefik.http.routers.stgtrails-app.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.stgtrails-app.ruleSyntax=v3'

volumes:
  sqlite:
    driver: local
