services:
  feeds-app:
    image: feeds-app
    build:
      context: ../../
      dockerfile: apps/feeds/feeds-app/Dockerfile
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - database
    environment:
      JWT_ACCESS_TOKEN_SECRET: local_access_secret
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 3600s
      JWT_REFRESH_TOKEN_SECRET: local_refresh_secret
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 604800s
      FEEDS_DATABASE_URL: postgres://postgres:local_db_password@database/feeds
      ADMIN_USER: root
      ADMIN_PASSWORD: local_admin_password

  database:
    restart: always
    image: postgres:16-alpine
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_db_password
      POSTGRES_DB: feeds
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
