version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: feeds
    ports:
      - '5434:5432'
