GET http://localhost:3333/api/feed
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST http://localhost:3333/api/feed/discover
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "url": "https://www.mtb-news.de"
}

###

POST http://localhost:3333/api/feed
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "MTB-News.de",
  "url": "https://www.mtb-news.de",
  "feedUrl": "https://www.mtb-news.de/feed/"
}

###

POST http://localhost:3333/api/feed/discover
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "url": "https://arstechnica.com"
}

###

POST http://localhost:3333/api/feed
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "Ars Technica",
  "url": "https://arstechnica.com",
  "feedUrl": "http://feeds.arstechnica.com/arstechnica/index/"
}

###

POST http://localhost:3333/api/feed/discover
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "url": "https://heise.de"
}

###

POST http://localhost:3333/api/feed
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "heise online News",
  "url": "https://heise.de",
  "feedUrl": "https://www.heise.de/rss/heise.rdf"
}

###

POST http://localhost:3333/api/feed/discover
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "url": "https://www.youtube.com/c/iskall85/videos"
}

###
