GET http://localhost:3333/api/feed
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# MTB-News.de
GET http://localhost:3333/api/feed/b8ca290b-bc14-44c7-8037-cfcc0686bcd0
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# Ars Technica
GET http://localhost:3333/api/feed/51d389c8-46a4-4dbe-92af-4616604a884a
Accept: application/json
Authorization: Bearer {{auth_token}}

###
