GET http://localhost:3333/api/feed
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# MTB-News.de
GET http://localhost:3333/api/feed/78de9625-dae7-402c-ac3e-7ea783800537
Accept: application/json
Authorization: Bearer {{auth_token}}

###

# Ars Technica
GET http://localhost:3333/api/feed/dbf1ff52-f01c-4a6b-96eb-4e987605ede2
#GET http://localhost:3333/api/feed/dbf1ff52-f01c-4a6b-96eb-4e987605ede2
Accept: application/json
Authorization: Bearer {{auth_token}}

###
