POST http://localhost:3333/api/authentication/login
Content-Type: application/json

{
  "username": "root",
  "password": "local_admin_password"
}

> {%
  client.global.set("auth_token", response.body.access_token)
%}

###
POST http://localhost:3333/api/scheduling/now
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET http://localhost:3333/api/admin/stats
Accept: application/json
Authorization: Bearer {{auth_token}}

###
