POST http://localhost:3333/api/authentication/register
Content-Type: application/json

{
  "username": "user",
  "password": "just_secret"
}

###
POST http://localhost:3333/api/authentication/login
Content-Type: application/json

{
  "username": "user",
  "password": "just_secret"
}

> {%
  client.global.set("auth_token", response.body.access_token)
  client.global.set("refresh_token", response.body.refresh_token)
%}

###
GET http://localhost:3333/api/authentication/profile
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:3333/api/authentication/refresh
Accept: application/json
Authorization: Bearer {{refresh_token}}

###
