/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesMacAddressRouteImport } from './routes/devices/$macAddress'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesMacAddressRoute = DevicesMacAddressRouteImport.update({
  id: '/devices/$macAddress',
  path: '/devices/$macAddress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/discovery': typeof DiscoveryRoute
  '/settings': typeof SettingsRoute
  '/devices/$macAddress': typeof DevicesMacAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/discovery': typeof DiscoveryRoute
  '/settings': typeof SettingsRoute
  '/devices/$macAddress': typeof DevicesMacAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/discovery': typeof DiscoveryRoute
  '/settings': typeof SettingsRoute
  '/devices/$macAddress': typeof DevicesMacAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/commands' | '/discovery' | '/settings' | '/devices/$macAddress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/commands' | '/discovery' | '/settings' | '/devices/$macAddress'
  id: '__root__' | '/' | '/commands' | '/discovery' | '/settings' | '/devices/$macAddress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandsRoute: typeof CommandsRoute
  DiscoveryRoute: typeof DiscoveryRoute
  SettingsRoute: typeof SettingsRoute
  DevicesMacAddressRoute: typeof DevicesMacAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$macAddress': {
      id: '/devices/$macAddress'
      path: '/devices/$macAddress'
      fullPath: '/devices/$macAddress'
      preLoaderRoute: typeof DevicesMacAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandsRoute: CommandsRoute,
  DiscoveryRoute: DiscoveryRoute,
  SettingsRoute: SettingsRoute,
  DevicesMacAddressRoute: DevicesMacAddressRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
