name: Nx affected
description: Run a Nx task for the affected applications/libraries

inputs:
  target:
    description: Nx target to run
    required: true

  parallel:
    description: How many jobs to run in parallel
    default: '1'

  configuration:
    description: Configuration to use for target, e.g. 'development' or 'production'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    # We are on a pull request, so compare to target
    - run: npx nx affected --base origin/main --target ${{ inputs.target }} --configuration ${{ inputs.configuration }} --parallel ${{ inputs.parallel }}
      if: ${{ github.base_ref == 'main' }}
      shell: bash

    # We are on the main branch, so compare to the last commit
    - run: npx nx affected --base HEAD~1 --target ${{ inputs.target }} --configuration ${{ inputs.configuration }} --parallel ${{ inputs.parallel }}
      if: ${{ github.base_ref != 'main' }}
      shell: bash
