import { http, HttpResponse } from 'msw'

import { xmlBuilder } from '../avm/shared'

export const tr64descXmlSpec = http.get('https://fritz-test.box:49443/tr64desc.xml', () => {
  return HttpResponse.xml(
    xmlBuilder.build({
      '?xml': { '@@version': '1.0' },
      root: {
        specVersion: { major: 1, minor: 0 },
        systemVersion: {
          HW: 267,
          Major: 267,
          Minor: 7,
          Patch: 57,
          Buildnumber: 107843,
          Display: '267.07.57',
        },
        device: {
          deviceType: 'urn:dslforum-org:device:InternetGatewayDevice:1',
          friendlyName: 'FRITZ!Box 6690 Cable',
          manufacturer: 'AVM',
          manufacturerURL: 'www.avm.de',
          modelDescription: 'FRITZ!Box 6690 Cable',
          modelName: 'FRITZ!Box 6690 Cable',
          modelNumber: '6690 - avm',
          modelURL: 'www.avm.de',
          UDN: 'uuid:1d9b79ec-f781-4dcc-8e5b-98862cd46221',
          serialNumber: 'AA:BB:CC:DD:EE:FF',
          originUDN: '',
          iconList: {
            icon: {
              mimetype: 'image/gif',
              width: 118,
              height: 119,
              depth: 8,
              url: '/ligd.gif',
            },
          },
          serviceList: {
            service: [
              // {
              //   serviceType: 'urn:dslforum-org:service:DeviceInfo:1',
              //   serviceId: 'urn:DeviceInfo-com:serviceId:DeviceInfo1',
              //   controlURL: '/upnp/control/deviceinfo',
              //   eventSubURL: '/upnp/control/deviceinfo',
              //   SCPDURL: '/deviceinfoSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:DeviceConfig:1',
              //   serviceId: 'urn:DeviceConfig-com:serviceId:DeviceConfig1',
              //   controlURL: '/upnp/control/deviceconfig',
              //   eventSubURL: '/upnp/control/deviceconfig',
              //   SCPDURL: '/deviceconfigSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:Layer3Forwarding:1',
              //   serviceId: 'urn:Layer3Forwarding-com:serviceId:Layer3Forwarding1',
              //   controlURL: '/upnp/control/layer3forwarding',
              //   eventSubURL: '/upnp/control/layer3forwarding',
              //   SCPDURL: '/layer3forwardingSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:LANConfigSecurity:1',
              //   serviceId: 'urn:LANConfigSecurity-com:serviceId:LANConfigSecurity1',
              //   controlURL: '/upnp/control/lanconfigsecurity',
              //   eventSubURL: '/upnp/control/lanconfigsecurity',
              //   SCPDURL: '/lanconfigsecuritySCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:ManagementServer:1',
              //   serviceId: 'urn:ManagementServer-com:serviceId:ManagementServer1',
              //   controlURL: '/upnp/control/mgmsrv',
              //   eventSubURL: '/upnp/control/mgmsrv',
              //   SCPDURL: '/mgmsrvSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:Time:1',
              //   serviceId: 'urn:Time-com:serviceId:Time1',
              //   controlURL: '/upnp/control/time',
              //   eventSubURL: '/upnp/control/time',
              //   SCPDURL: '/timeSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:UserInterface:1',
              //   serviceId: 'urn:UserInterface-com:serviceId:UserInterface1',
              //   controlURL: '/upnp/control/userif',
              //   eventSubURL: '/upnp/control/userif',
              //   SCPDURL: '/userifSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Storage:1',
              //   serviceId: 'urn:X_AVM-DE_Storage-com:serviceId:X_AVM-DE_Storage1',
              //   controlURL: '/upnp/control/x_storage',
              //   eventSubURL: '/upnp/control/x_storage',
              //   SCPDURL: '/x_storageSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_WebDAVClient:1',
              //   serviceId: 'urn:X_AVM-DE_WebDAV-com:serviceId:X_AVM-DE_WebDAVClient1',
              //   controlURL: '/upnp/control/x_webdav',
              //   eventSubURL: '/upnp/control/x_webdav',
              //   SCPDURL: '/x_webdavSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_UPnP:1',
              //   serviceId: 'urn:X_AVM-DE_UPnP-com:serviceId:X_AVM-DE_UPnP1',
              //   controlURL: '/upnp/control/x_upnp',
              //   eventSubURL: '/upnp/control/x_upnp',
              //   SCPDURL: '/x_upnpSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Speedtest:1',
              //   serviceId: 'urn:X_AVM-DE_Speedtest-com:serviceId:X_AVM-DE_Speedtest1',
              //   controlURL: '/upnp/control/x_speedtest',
              //   eventSubURL: '/upnp/control/x_speedtest',
              //   SCPDURL: '/x_speedtestSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_RemoteAccess:1',
              //   serviceId: 'urn:X_AVM-DE_RemoteAccess-com:serviceId:X_AVM-DE_RemoteAccess1',
              //   controlURL: '/upnp/control/x_remote',
              //   eventSubURL: '/upnp/control/x_remote',
              //   SCPDURL: '/x_remoteSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_MyFritz:1',
              //   serviceId: 'urn:X_AVM-DE_MyFritz-com:serviceId:X_AVM-DE_MyFritz1',
              //   controlURL: '/upnp/control/x_myfritz',
              //   eventSubURL: '/upnp/control/x_myfritz',
              //   SCPDURL: '/x_myfritzSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_VoIP:1',
              //   serviceId: 'urn:X_VoIP-com:serviceId:X_VoIP1',
              //   controlURL: '/upnp/control/x_voip',
              //   eventSubURL: '/upnp/control/x_voip',
              //   SCPDURL: '/x_voipSCPD.xml',
              // },
              {
                serviceType: 'urn:dslforum-org:service:X_AVM-DE_OnTel:1',
                serviceId: 'urn:X_AVM-DE_OnTel-com:serviceId:X_AVM-DE_OnTel1',
                controlURL: '/upnp/control/x_contact',
                eventSubURL: '/upnp/control/x_contact',
                SCPDURL: '/x_contactSCPD.xml',
              },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Dect:1',
              //   serviceId: 'urn:X_AVM-DE_Dect-com:serviceId:X_AVM-DE_Dect1',
              //   controlURL: '/upnp/control/x_dect',
              //   eventSubURL: '/upnp/control/x_dect',
              //   SCPDURL: '/x_dectSCPD.xml',
              // },
              {
                serviceType: 'urn:dslforum-org:service:X_AVM-DE_TAM:1',
                serviceId: 'urn:X_AVM-DE_TAM-com:serviceId:X_AVM-DE_TAM1',
                controlURL: '/upnp/control/x_tam',
                eventSubURL: '/upnp/control/x_tam',
                SCPDURL: '/x_tamSCPD.xml',
              },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_AppSetup:1',
              //   serviceId: 'urn:X_AVM-DE_AppSetup-com:serviceId:X_AVM-DE_AppSetup1',
              //   controlURL: '/upnp/control/x_appsetup',
              //   eventSubURL: '/upnp/control/x_appsetup',
              //   SCPDURL: '/x_appsetupSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Homeauto:1',
              //   serviceId: 'urn:X_AVM-DE_Homeauto-com:serviceId:X_AVM-DE_Homeauto1',
              //   controlURL: '/upnp/control/x_homeauto',
              //   eventSubURL: '/upnp/control/x_homeauto',
              //   SCPDURL: '/x_homeautoSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Homeplug:1',
              //   serviceId: 'urn:X_AVM-DE_Homeplug-com:serviceId:X_AVM-DE_Homeplug1',
              //   controlURL: '/upnp/control/x_homeplug',
              //   eventSubURL: '/upnp/control/x_homeplug',
              //   SCPDURL: '/x_homeplugSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Filelinks:1',
              //   serviceId: 'urn:X_AVM-DE_Filelinks-com:serviceId:X_AVM-DE_Filelinks1',
              //   controlURL: '/upnp/control/x_filelinks',
              //   eventSubURL: '/upnp/control/x_filelinks',
              //   SCPDURL: '/x_filelinksSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Auth:1',
              //   serviceId: 'urn:X_AVM-DE_Auth-com:serviceId:X_AVM-DE_Auth1',
              //   controlURL: '/upnp/control/x_auth',
              //   eventSubURL: '/upnp/control/x_auth',
              //   SCPDURL: '/x_authSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_HostFilter:1',
              //   serviceId: 'urn:X_AVM-DE_HostFilter-com:serviceId:X_AVM-DE_HostFilter1',
              //   controlURL: '/upnp/control/x_hostfilter',
              //   eventSubURL: '/upnp/control/x_hostfilter',
              //   SCPDURL: '/x_hostfilterSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_Media:1',
              //   serviceId: 'urn:X_AVM-DE_Media-com:serviceId:X_AVM-DE_Media1',
              //   controlURL: '/upnp/control/x_media',
              //   eventSubURL: '/upnp/control/x_media',
              //   SCPDURL: '/x_mediaSCPD.xml',
              // },
              // {
              //   serviceType: 'urn:dslforum-org:service:X_AVM-DE_USPController:1',
              //   serviceId: 'urn:X_AVM-DE_USPController-com:serviceId:X_AVM-DE_USPController1',
              //   controlURL: '/upnp/control/x_uspcontroller',
              //   eventSubURL: '/upnp/control/x_uspcontroller',
              //   SCPDURL: '/x_uspcontrollerSCPD.xml',
              // },
            ],
          },
          deviceList: {
            device: [
              {
                deviceType: 'urn:dslforum-org:device:LANDevice:1',
                friendlyName: 'LANDevice - FRITZ!Box 6690 Cable',
                manufacturer: 'AVM',
                manufacturerURL: 'www.avm.de',
                modelDescription: 'LANDevice - FRITZ!Box 6690 Cable',
                modelName: 'LANDevice - FRITZ!Box 6690 Cable',
                modelNumber: '6690 - avm',
                modelURL: 'www.avm.de',
                UDN: 'uuid:1d9b79ec-f781-4dcc-8e5b-98862cd46221',
                UPC: 'AVM TR-064',
                serviceList: {
                  service: [
                    {
                      serviceType: 'urn:dslforum-org:service:WLANConfiguration:1',
                      serviceId: 'urn:WLANConfiguration-com:serviceId:WLANConfiguration1',
                      controlURL: '/upnp/control/wlanconfig1',
                      eventSubURL: '/upnp/control/wlanconfig1',
                      SCPDURL: '/wlanconfigSCPD.xml',
                    },
                    {
                      serviceType: 'urn:dslforum-org:service:WLANConfiguration:2',
                      serviceId: 'urn:WLANConfiguration-com:serviceId:WLANConfiguration2',
                      controlURL: '/upnp/control/wlanconfig2',
                      eventSubURL: '/upnp/control/wlanconfig2',
                      SCPDURL: '/wlanconfigSCPD.xml',
                    },
                    {
                      serviceType: 'urn:dslforum-org:service:WLANConfiguration:3',
                      serviceId: 'urn:WLANConfiguration-com:serviceId:WLANConfiguration3',
                      controlURL: '/upnp/control/wlanconfig3',
                      eventSubURL: '/upnp/control/wlanconfig3',
                      SCPDURL: '/wlanconfigSCPD.xml',
                    },
                    {
                      serviceType: 'urn:dslforum-org:service:Hosts:1',
                      serviceId: 'urn:LanDeviceHosts-com:serviceId:Hosts1',
                      controlURL: '/upnp/control/hosts',
                      eventSubURL: '/upnp/control/hosts',
                      SCPDURL: '/hostsSCPD.xml',
                    },
                    {
                      serviceType: 'urn:dslforum-org:service:LANEthernetInterfaceConfig:1',
                      serviceId: 'urn:LANEthernetIfCfg-com:serviceId:LANEthernetInterfaceConfig1',
                      controlURL: '/upnp/control/lanethernetifcfg',
                      eventSubURL: '/upnp/control/lanethernetifcfg',
                      SCPDURL: '/ethifconfigSCPD.xml',
                    },
                    {
                      serviceType: 'urn:dslforum-org:service:LANHostConfigManagement:1',
                      serviceId: 'urn:LANHCfgMgm-com:serviceId:LANHostConfigManagement1',
                      controlURL: '/upnp/control/lanhostconfigmgm',
                      eventSubURL: '/upnp/control/lanhostconfigmgm',
                      SCPDURL: '/lanhostconfigmgmSCPD.xml',
                    },
                  ],
                },
              },
              {
                deviceType: 'urn:dslforum-org:device:WANDevice:1',
                friendlyName: 'WANDevice - FRITZ!Box 6690 Cable',
                manufacturer: 'AVM',
                manufacturerURL: 'www.avm.de',
                modelDescription: 'WANDevice - FRITZ!Box 6690 Cable',
                modelName: 'WANDevice - FRITZ!Box 6690 Cable',
                modelNumber: '6690 - avm',
                modelURL: 'www.avm.de',
                UDN: 'uuid:75802409-bccb-40e7-8e6a-B0F20803645C',
                UPC: 'AVM TR-064',
                serviceList: {
                  service: [
                    {
                      serviceType: 'urn:dslforum-org:service:WANCommonInterfaceConfig:1',
                      serviceId: 'urn:WANCIfConfig-com:serviceId:WANCommonInterfaceConfig1',
                      controlURL: '/upnp/control/wancommonifconfig1',
                      eventSubURL: '/upnp/control/wancommonifconfig1',
                      SCPDURL: '/wancommonifconfigSCPD.xml',
                    },
                    {
                      serviceType: 'urn:dslforum-org:service:WANDSLInterfaceConfig:1',
                      serviceId: 'urn:WANDSLIfConfig-com:serviceId:WANDSLInterfaceConfig1',
                      controlURL: '/upnp/control/wandslifconfig1',
                      eventSubURL: '/upnp/control/wandslifconfig1',
                      SCPDURL: '/wandslifconfigSCPD.xml',
                    },
                  ],
                },
                deviceList: {
                  device: {
                    deviceType: 'urn:dslforum-org:device:WANConnectionDevice:1',
                    friendlyName: 'WANConnectionDevice - FRITZ!Box 6690 Cable',
                    manufacturer: 'AVM',
                    manufacturerURL: 'www.avm.de',
                    modelDescription: 'WANConnectionDevice - FRITZ!Box 6690 Cable',
                    modelName: 'WANConnectionDevice - FRITZ!Box 6690 Cable',
                    modelNumber: '6690 - avm',
                    modelURL: 'www.avm.de',
                    UDN: 'uuid:1d9b79ec-f781-4dcc-8e5b-98862cd46221',
                    UPC: 'AVM TR-064',
                    serviceList: {
                      service: {
                        service: [
                          {
                            serviceType: 'urn:dslforum-org:service:X_AVM-DE_WANMobileConnection:1',
                            serviceId: 'urn:X_AVM-DE_WANMobileConnection-com:serviceId:X_AVM-DE_WANMobileConnection1',
                            controlURL: '/upnp/control/x_wanmobileconn',
                            eventSubURL: '/upnp/control/x_wanmobileconn',
                            SCPDURL: '/x_wanmobileconnSCPD.xml',
                          },
                          {
                            serviceType: 'urn:dslforum-org:service:WANDSLLinkConfig:1',
                            serviceId: 'urn:WANDSLLinkConfig-com:serviceId:WANDSLLinkConfig1',
                            controlURL: '/upnp/control/wandsllinkconfig1',
                            eventSubURL: '/upnp/control/wandsllinkconfig1',
                            SCPDURL: '/wandsllinkconfigSCPD.xml',
                          },
                          {
                            serviceType: 'urn:dslforum-org:service:WANEthernetLinkConfig:1',
                            serviceId: 'urn:WANEthernetLinkConfig-com:serviceId:WANEthernetLinkConfig1',
                            controlURL: '/upnp/control/wanethlinkconfig1',
                            eventSubURL: '/upnp/control/wanethlinkconfig1',
                            SCPDURL: '/wanethlinkconfigSCPD.xml',
                          },
                          {
                            serviceType: 'urn:dslforum-org:service:WANPPPConnection:1',
                            serviceId: 'urn:WANPPPConnection-com:serviceId:WANPPPConnection1',
                            controlURL: '/upnp/control/wanpppconn1',
                            eventSubURL: '/upnp/control/wanpppconn1',
                            SCPDURL: '/wanpppconnSCPD.xml',
                          },
                          {
                            serviceType: 'urn:dslforum-org:service:WANIPConnection:1',
                            serviceId: 'urn:WANIPConnection-com:serviceId:WANIPConnection1',
                            controlURL: '/upnp/control/wanipconnection1',
                            eventSubURL: '/upnp/control/wanipconnection1',
                            SCPDURL: '/wanipconnSCPD.xml',
                          },
                        ],
                      },
                    },
                  },
                },
              },
            ],
          },
          presentationURL: 'http://fritz-test.box',
        },
        '@@xmlns': 'urn:dslforum-org:device-1-0',
      },
    }),
  )
})
