name: Run renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # At 07:00 everyday
permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '16'

      - name: 'Install & Run Renovate Bot'
        run: |
          npm install -g renovate
          renovate mgansler/plusone --token=${PERSONAL_ACCESS_TOKEN}
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
