name: Verify
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ['build', 'component-test', 'lint', 'test']
        include:
          - target: build
            configuration: production
            parallel: 1
          - target: component-test
            parallel: 1
          - target: lint
            parallel: 4
          - target: test
            parallel: 4

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Prepare NodeJS
        uses: ./.github/actions/prepare-nodejs

      - name: Nx affected --target ${{ matrix.target }}
        uses: ./.github/actions/nx-affected
        with:
          target: ${{ matrix.target }}
          configuration: ${{ matrix.configuration }}
          parallel: ${{ matrix.parallel }}

  affected-e2e:
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{ steps.affected-apps.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Prepare NodeJS
        uses: ./.github/actions/prepare-nodejs

      - name: Determine affected e2e projects
        id: affected-apps
        run: |2-
          if [ '${{ github.base_ref }}' == 'main' ]; then
            baseRef=origin/main
          else
            baseRef=HEAD~1
          fi

          npx nx show projects --base ${baseRef} --affected --withTarget e2e

          # Output must be ["string","string"] with no spaces.
          affectedApps=$(npx nx show projects --base ${baseRef} --affected --withTarget e2e --json | jq -c)
          echo "affected_apps=${affectedApps}" >> ${GITHUB_OUTPUT}

  # E2E tests use their own matrix so that each of them can be retried independently
  e2e:
    runs-on: ubuntu-latest
    needs: affected-e2e
    if: ${{ needs.affected-e2e.outputs.affected_apps != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson( needs.affected-e2e.outputs.affected_apps ) }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Prepare NodeJS
        uses: ./.github/actions/prepare-nodejs

      - name: Run ${{ matrix.project }}:e2e
        timeout-minutes: 15
        continue-on-error: ${{ matrix.project == 'advent-of-code-2021-e2e' }}
        run: npx nx run ${{ matrix.project }}:e2e
